# Generated by Django 4.2.30 on 2026-08-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Top-level league admin: manage commissioners, Django admin, and all commissioner tools.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_commissioner',
            field=models.BooleanField(default=False, help_text='League ops: teams, schedule, scores, captains.'),
        ),
    ]
