# Generated by Django 4.2.30 on 2026-08-07 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_player_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['abbrev', 'name']},
        ),
        migrations.RemoveField(
            model_name='player',
            name='phone',
        ),
    ]
